project-key: MIN

name: minerva

parameters:

  # Cloud setup
#  data_dir: /public/whales
#  solution_dir: /output/resources/whales/solution/classification

  # Local setup
  data_dir: path/to/your/data # for instance resources/whales/data
  solution_dir:  path/to/your/solution # for instance resources/whales/solution/localization

exclude:
  - resources
  - output
  - neptune.log
  - offline_job.log
  - .idea
  - .git
  - .ipynb_checkpoints

# Comment if local
# pip-requirements-file: requirements.txt
