project-key: MIN

name: minerva

parameters:

  # Local setup
#  data_dir: resources/whales/data # for instance resources/whales/data
#  solution_dir:  output/path_to_your_solution # for instance /output/resources/whales/solution/localization

  # Cloud setup
#  data_dir: /public/whales # for instance /public/whales
#  solution_dir: /output/path_to_your_solution # /output/path_to_your_solution

exclude:
  - resources
  - output
  - neptune.log
  - offline_job.log
  - .idea
  - .git
  - .ipynb_checkpoints

# Comment if local
pip-requirements-file: requirements.txt